Comment out nuclear test for now

diff --git a/.github/workflows/extended-complement-tests-metrics.yml b/.github/workflows/extended-complement-tests-metrics.yml
--- a/.github/workflows/extended-complement-tests-metrics.yml
+++ b/.github/workflows/extended-complement-tests-metrics.yml
@@ -134,41 +134,41 @@ jobs:
           set -o pipefail
           COMPLEMENT_DIR=`pwd`/complement synapse/scripts-dev/complement-extended.sh -json 2>&1 | synapse/.ci/scripts/gotestfmt
 
-  nuclear:
-    name: "Overload GitHub"
-    runs-on: ubuntu-latest
-    needs: calculate-test-jobs
-    strategy:
-      fail-fast: false
-      matrix:
-        job: ${{ fromJson(needs.calculate-test-jobs.outputs.complement_nuclear_test_matrix) }}
+#  nuclear:
+#    name: "Overload GitHub"
+#    runs-on: ubuntu-latest
+#    needs: calculate-test-jobs
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        job: ${{ fromJson(needs.calculate-test-jobs.outputs.complement_nuclear_test_matrix) }}
 
-    steps:
-      - name: Run actions/checkout@v3 for synapse
-        uses: actions/checkout@v3
-        with:
-          path: synapse
+#    steps:
+#      - name: Run actions/checkout@v3 for synapse
+#        uses: actions/checkout@v3
+#        with:
+#          path: synapse
 
-      - name: Install Rust
-        uses: actions-rs/toolchain@v1
-        with:
-            toolchain: 1.58.1
-            override: true
-      - uses: Swatinem/rust-cache@v2
+#      - name: Install Rust
+#        uses: actions-rs/toolchain@v1
+#        with:
+#            toolchain: 1.58.1
+#            override: true
+#      - uses: Swatinem/rust-cache@v2
+#
+#      - name: Prepare Complement's Prerequisites
+#        run: synapse/.ci/scripts/setup_complement_prerequisites.sh
 
-      - name: Prepare Complement's Prerequisites
-        run: synapse/.ci/scripts/setup_complement_prerequisites.sh
-
-      - shell: bash
-        name: Run Complement Tests
-        env:
-          POSTGRES: "true"
-          WORKERS: "true"
-          SYNAPSE_METRICS: "true"
-          SYNAPSE_WORKER_TYPES: ${{ matrix.job.worker_types }}
-        run: |
-          set -o pipefail
-          COMPLEMENT_DIR=`pwd`/complement synapse/scripts-dev/complement-extended.sh -json 2>&1 | synapse/.ci/scripts/gotestfmt
+#      - shell: bash
+#        name: Run Complement Tests
+#        env:
+#          POSTGRES: "true"
+#          WORKERS: "true"
+#          SYNAPSE_METRICS: "true"
+#          SYNAPSE_WORKER_TYPES: ${{ matrix.job.worker_types }}
+#        run: |
+#          set -o pipefail
+#          COMPLEMENT_DIR=`pwd`/complement synapse/scripts-dev/complement-extended.sh -json 2>&1 | synapse/.ci/scripts/gotestfmt
 
   # a job which marks all the other jobs as complete, and only pings my phone on error.
   tests-done:
