[CI] Enable more pypy tests with latest deps.

diff --git a/.github/workflows/pypytests.yml b/.github/workflows/pypytests.yml
--- a/.github/workflows/pypytests.yml
+++ b/.github/workflows/pypytests.yml
@@ -298,58 +298,79 @@ jobs:
           || true
 
 
-#  trial-pypy:
-    # Very slow; only run if the branch name includes 'pypy'
-    # Note: sqlite only; no postgres. Completely untested since poetry move.
-#    if: ${{ contains(github.ref, 'pypy') && !failure() && !cancelled() }}
-#    needs: linting-done
+  mypy-latest-deps:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - name: Install Rust
+        uses: actions-rs/toolchain@v1
+        with:
+            toolchain: stable
+            override: true
+      - uses: Swatinem/rust-cache@v2
+
+      # The dev dependencies aren't exposed in the wheel metadata (at least with current
+      # poetry-core versions), so we install with poetry.
+      - uses: matrix-org/setup-python-poetry@dmr/try-newer-actions
+        with:
+          python-version: "pypy3.9"
+          poetry-version: "1.2.0"
+          extras: "all"
+      # Dump installed versions for debugging.
+      - run: poetry run pip list > before.txt
+      # Upgrade all runtime dependencies only. This is intended to mimic a fresh
+      # `pip install matrix-synapse[all]` as closely as possible.
+      - run: poetry update --no-dev
+      - run: poetry run pip list > after.txt && (diff -u before.txt after.txt || true)
+      - name: Remove warn_unused_ignores from mypy config
+        run: sed '/warn_unused_ignores = True/d' -i mypy.ini
+      - run: poetry run mypy
+
+#  trial-latest-deps:
+#  NOTE: this doesn't work as pympler is used for memory profiling and doesn't
+#  support pypy. Pypy doesn't use sys.getsizeof which pympler relies on to get
+#  a __itemsize___ attribute.
+#    if: ${{ !cancelled() && !failure() }} # Allow previous steps to be skipped, but not fail
 #    runs-on: ubuntu-latest
+#    needs: calculate-pypy-test-jobs
 #    strategy:
 #      matrix:
-#        python-version: ["pypy3.8", "pypy3.9"]
-#        database: ["sqlite"]
-#        extras: ["all"]
-#        include:
-          # Oldest Python with PostgreSQL
-#          - python-version: "pypy3.9"
-#            database: "postgres"
-#            postgres-version: "10"
-#            extras: "all"
-
-          # Newest Python with newest PostgreSQL
-#          - python-version: "pypy3.9"
-#            database: "postgres"
-#            postgres-version: "14"
-#            extras: "all"
-
+#        job: ${{ fromJson(needs.calculate-pypy-test-jobs.outputs.trial_test_matrix) }}
 #    steps:
 #      - uses: actions/checkout@v3
-      # Install libs necessary for PyPy to build binary wheels for dependencies
+#      - name: Install Rust
+#        uses: actions-rs/toolchain@v1
+#        with:
+#            toolchain: stable
+#            override: true
+#      - uses: Swatinem/rust-cache@v2
 #      - run: sudo apt-get -qq install xmlsec1 libxml2-dev libxslt-dev
-#      - name: Set up PostgreSQL ${{ matrix.postgres-version }}
-#        if: ${{ matrix.postgres-version }}
+#      - name: Set up PostgreSQL ${{ matrix.job.postgres-version }}
+#        if: ${{ matrix.job.postgres-version }}
 #        run: |
 #          docker run -d -p 5432:5432 \
 #            -e POSTGRES_PASSWORD=postgres \
 #            -e POSTGRES_INITDB_ARGS="--lc-collate C --lc-ctype C --encoding UTF8" \
-#            postgres:${{ matrix.postgres-version }}
-
-#      - uses: matrix-org/setup-python-poetry@dmr/try-newer-actions
+#            postgres:${{ matrix.job.postgres-version }}
+#      - uses: actions/setup-python@v4
 #        with:
-#          python-version: ${{ matrix.python-version }}
-#          extras: ${{ matrix.extras }}
+#          python-version: ${{ matrix.job.python-version }}
+#      - run: pip install .[all,test]
 #      - name: Await PostgreSQL
-#        if: ${{ matrix.postgres-version }}
+#        if: ${{ matrix.job.postgres-version }}
 #        timeout-minutes: 2
 #        run: until pg_isready -h localhost; do sleep 1; done
 
-#      - run: poetry run trial --jobs=2 tests
+      # We nuke the local copy, as we've installed synapse into the virtualenv
+      # (rather than use an editable install, which we no longer support). If we
+      # don't do this then python can't find the native lib.
+#      - run: rm -rf synapse/
+#      - run: python -m twisted.trial --jobs=2 tests
 #        env:
-#          SYNAPSE_POSTGRES: ${{ matrix.database == 'postgres' || '' }}
+#          SYNAPSE_POSTGRES: ${{ matrix.jobs.database == 'postgres' || '' }}
 #          SYNAPSE_POSTGRES_HOST: localhost
 #          SYNAPSE_POSTGRES_USER: postgres
 #          SYNAPSE_POSTGRES_PASSWORD: postgres
-
 #      - name: Dump logs
         # Logs are most useful when the command fails, always include them.
 #        if: ${{ always() }}
@@ -362,6 +383,7 @@ jobs:
 #          -exec cat {} \;
 #          -exec echo "::endgroup::" \;
 #          || true
+
 
   sytest:
     if: ${{ !failure() && !cancelled() }}
@@ -397,6 +419,55 @@ jobs:
             override: true
       - uses: Swatinem/rust-cache@v2
 
+      - name: Run SyTest
+        run: /bootstrap.sh synapse
+        working-directory: /src
+      - name: Summarise results.tap
+        if: ${{ always() }}
+        run: /sytest/scripts/tap_to_gha.pl /logs/results.tap
+      - name: Upload SyTest logs
+        uses: actions/upload-artifact@v3
+        if: ${{ always() }}
+        with:
+          name: Sytest Logs - ${{ job.status }} - (${{ join(matrix.job.*, ', ') }})
+          path: |
+            /logs/results.tap
+            /logs/**/*.log*
+
+  sytest-latest-deps:
+    if: ${{ !failure() && !cancelled() }}
+    needs: calculate-pypy-test-jobs
+    runs-on: ubuntu-latest
+    container:
+      image: matrixdotorg/sytest-synapse:${{ matrix.job.sytest-tag }}
+      volumes:
+        - ${{ github.workspace }}:/src
+      env:
+        SYTEST_BRANCH: ${{ github.head_ref }}
+        POSTGRES: ${{ matrix.job.postgres && 1 }}
+        MULTI_POSTGRES: ${{ (matrix.job.postgres == 'multi-postgres') && 1 }}
+        WORKERS: ${{ matrix.job.workers && 1 }}
+        BLACKLIST: ${{ matrix.job.workers && 'synapse-blacklist-with-workers' }}
+        TOP: ${{ github.workspace }}
+    strategy:
+      fail-fast: false
+      matrix:
+        job: ${{ fromJson(needs.calculate-pypy-test-jobs.outputs.sytest_test_matrix) }}
+    steps:
+      - uses: actions/checkout@v3
+      - run: apt-get -qq install xmlsec1 libxml2-dev libxslt-dev
+      - name: Prepare test blacklist
+        run: cat sytest-blacklist .ci/worker-blacklist > synapse-blacklist-with-workers
+      - name: Install Rust
+        uses: actions-rs/toolchain@v1
+        with:
+            toolchain: 1.61.0
+            override: true
+      - uses: Swatinem/rust-cache@v2
+      - name: Ensure sytest runs `pip install`
+        # Delete the lockfile so sytest will `pip install` rather than `poetry install`
+        run: rm /src/poetry.lock
+        working-directory: /src
       - name: Run SyTest
         run: /bootstrap.sh synapse
         working-directory: /src
