[CI] Disable lint-newsfile, trial-pypy, and Sytest.Edited Sytest bits for when it's ready.

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -40,19 +40,19 @@ jobs:
       - name: Check line endings
         run: scripts-dev/check_line_terminators.sh
 
-  lint-newsfile:
-    if: ${{ github.base_ref == 'develop'  || contains(github.base_ref, 'release-') }}
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
-        with:
-          ref: ${{ github.event.pull_request.head.sha }}
-          fetch-depth: 0
-      - uses: actions/setup-python@v2
-      - run: "pip install 'towncrier>=18.6.0rc1'"
-      - run: scripts-dev/check-newsfragment.sh
-        env:
-          PULL_REQUEST_NUMBER: ${{ github.event.number }}
+  #lint-newsfile:
+  #  if: ${{ github.base_ref == 'develop'  || contains(github.base_ref, 'release-') }}
+  #  runs-on: ubuntu-latest
+  #  steps:
+  #    - uses: actions/checkout@v2
+  #      with:
+  #        ref: ${{ github.event.pull_request.head.sha }}
+  #        fetch-depth: 0
+  #    - uses: actions/setup-python@v2
+  #    - run: "pip install 'towncrier>=18.6.0rc1'"
+  #    - run: scripts-dev/check-newsfragment.sh
+  #      env:
+  #        PULL_REQUEST_NUMBER: ${{ github.event.number }}
 
   lint-pydantic:
     runs-on: ubuntu-latest
@@ -69,7 +69,8 @@ jobs:
   # Dummy step to gate other tests on without repeating the whole list
   linting-done:
     if: ${{ !cancelled() }} # Run this even if prior jobs were skipped
-    needs: [lint, lint-crlf, lint-newsfile, lint-pydantic, check-sampleconfig, check-schema-delta]
+#    needs: [lint, lint-crlf, lint-newsfile, lint-pydantic, check-sampleconfig, check-schema-delta]
+    needs: [lint, lint-crlf, lint-pydantic, check-sampleconfig, check-schema-delta]
     runs-on: ubuntu-latest
     steps:
       - run: "true"
@@ -80,7 +81,7 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        python-version: ["3.7", "3.8", "3.9", "3.10"]
+        python-version: ["3.9", "3.10"]
         database: ["sqlite"]
         extras: ["all"]
         include:
@@ -164,99 +165,115 @@ jobs:
           -exec echo "::endgroup::" \;
           || true
 
-  trial-pypy:
+#  trial-pypy:
     # Very slow; only run if the branch name includes 'pypy'
     # Note: sqlite only; no postgres. Completely untested since poetry move.
-    if: ${{ contains(github.ref, 'pypy') && !failure() && !cancelled() }}
-    needs: linting-done
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        python-version: ["pypy-3.7"]
-        extras: ["all"]
+#    if: ${{ contains(github.ref, 'pypy') && !failure() && !cancelled() }}
+#    needs: linting-done
+#    runs-on: ubuntu-latest
+#    strategy:
+#      matrix:
+#        python-version: ["pypy-3.7"]
+#        extras: ["all"]
 
-    steps:
-      - uses: actions/checkout@v2
+#    steps:
+#      - uses: actions/checkout@v2
       # Install libs necessary for PyPy to build binary wheels for dependencies
-      - run: sudo apt-get -qq install xmlsec1 libxml2-dev libxslt-dev
-      - uses: matrix-org/setup-python-poetry@v1
-        with:
-          python-version: ${{ matrix.python-version }}
-          extras: ${{ matrix.extras }}
-      - run: poetry run trial --jobs=2 tests
-      - name: Dump logs
+#      - run: sudo apt-get -qq install xmlsec1 libxml2-dev libxslt-dev
+#      - uses: matrix-org/setup-python-poetry@v1
+#        with:
+#          python-version: ${{ matrix.python-version }}
+#          extras: ${{ matrix.extras }}
+#      - run: poetry run trial --jobs=2 tests
+#      - name: Dump logs
         # Logs are most useful when the command fails, always include them.
-        if: ${{ always() }}
+#        if: ${{ always() }}
         # Note: Dumps to workflow logs instead of using actions/upload-artifact
         #       This keeps logs colocated with failing jobs
         #       It also ignores find's exit code; this is a best effort affair
-        run: >-
-          find _trial_temp -name '*.log'
-          -exec echo "::group::{}" \;
-          -exec cat {} \;
-          -exec echo "::endgroup::" \;
-          || true
+#        run: >-
+#          find _trial_temp -name '*.log'
+#          -exec echo "::group::{}" \;
+#          -exec cat {} \;
+#          -exec echo "::endgroup::" \;
+#          || true
 
-  sytest:
-    if: ${{ !failure() && !cancelled() }}
-    needs: linting-done
-    runs-on: ubuntu-latest
-    container:
-      image: matrixdotorg/sytest-synapse:${{ matrix.sytest-tag }}
-      volumes:
-        - ${{ github.workspace }}:/src
-      env:
-        SYTEST_BRANCH: ${{ github.head_ref }}
-        POSTGRES: ${{ matrix.postgres && 1}}
-        MULTI_POSTGRES: ${{ (matrix.postgres == 'multi-postgres') && 1}}
-        WORKERS: ${{ matrix.workers && 1 }}
-        REDIS: ${{ matrix.redis && 1 }}
-        BLACKLIST: ${{ matrix.workers && 'synapse-blacklist-with-workers' }}
-        TOP: ${{ github.workspace }}
-
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - sytest-tag: focal
-
-          - sytest-tag: focal
-            postgres: postgres
-
-          - sytest-tag: testing
-            postgres: postgres
-
-          - sytest-tag: focal
-            postgres: multi-postgres
-            workers: workers
-
-          - sytest-tag: buster
-            postgres: multi-postgres
-            workers: workers
-
-          - sytest-tag: buster
-            postgres: postgres
-            workers: workers
-            redis: redis
-
-    steps:
-      - uses: actions/checkout@v2
-      - name: Prepare test blacklist
-        run: cat sytest-blacklist .ci/worker-blacklist > synapse-blacklist-with-workers
-      - name: Run SyTest
-        run: /bootstrap.sh synapse
-        working-directory: /src
-      - name: Summarise results.tap
-        if: ${{ always() }}
-        run: /sytest/scripts/tap_to_gha.pl /logs/results.tap
-      - name: Upload SyTest logs
-        uses: actions/upload-artifact@v2
-        if: ${{ always() }}
-        with:
-          name: Sytest Logs - ${{ job.status }} - (${{ join(matrix.*, ', ') }})
-          path: |
-            /logs/results.tap
-            /logs/**/*.log*
+# This pulls the matrxdotorg image, not ours. Will need to fork to use.
+#  sytest:
+#    if: ${{ !failure() && !cancelled() }}
+#    needs: linting-done
+#    runs-on: ubuntu-latest
+#    container:
+#      image: matrixdotorg/sytest-synapse:${{ matrix.sytest-tag }}
+#      volumes:
+#        - ${{ github.workspace }}:/src
+#      env:
+#        SYTEST_BRANCH: ${{ github.head_ref }}
+#        POSTGRES: ${{ matrix.postgres && 1}}
+#        MULTI_POSTGRES: ${{ (matrix.postgres == 'multi-postgres') && 1}}
+#        WORKERS: ${{ matrix.workers && 1 }}
+#        REDIS: ${{ matrix.redis && 1 }}
+#        BLACKLIST: ${{ matrix.workers && 'synapse-blacklist-with-workers' }}
+#        TOP: ${{ github.workspace }}
+#
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        include:
+#          - sytest-tag: testing
+#            postgres: postgres
+#            workers: monolith
+#
+#          - sytest-tag: testing
+#            postgres: multi-postgres
+#            workers: monolith
+#
+#          - sytest-tag: buster
+#            postgres: postgres
+#            workers: monolith
+#
+#          - sytest-tag: buster
+#            postgres: multi-postgres
+#            workers: monolith
+#
+#          - sytest-tag: testing
+#            postgres: postgres
+#            workers: workers
+#            redis: redis
+#
+#          - sytest-tag: testing
+#            postgres: multi-postgres
+#            workers: workers
+#            redis: redis
+#
+#          - sytest-tag: buster
+#            postgres: postgres
+#            workers: workers
+#            redis: redis
+#
+#          - sytest-tag: buster
+#            postgres: multi-postgres
+#            workers: workers
+#            redis: redis
+#
+#    steps:
+#      - uses: actions/checkout@v2
+#      - name: Prepare test blacklist
+#        run: cat sytest-blacklist .ci/worker-blacklist > synapse-blacklist-with-workers
+#      - name: Run SyTest
+#        run: /bootstrap.sh synapse
+#        working-directory: /src
+#      - name: Summarise results.tap
+#        if: ${{ always() }}
+#        run: /sytest/scripts/tap_to_gha.pl /logs/results.tap
+#      - name: Upload SyTest logs
+#        uses: actions/upload-artifact@v2
+#        if: ${{ always() }}
+#        with:
+#          name: Sytest Logs - ${{ job.status }} - (${{ join(matrix.*, ', ') }})
+#          path: |
+#            /logs/results.tap
+#            /logs/**/*.log*
 
   export-data:
     if: ${{ !failure() && !cancelled() }} # Allow previous steps to be skipped, but not fail
@@ -366,10 +383,10 @@ jobs:
       - check-sampleconfig
       - lint
       - lint-crlf
-      - lint-newsfile
+#      - lint-newsfile
       - trial
       - trial-olddeps
-      - sytest
+#      - sytest
       - export-data
       - portdb
       - complement
@@ -380,5 +397,5 @@ jobs:
           needs: ${{ toJSON(needs) }}
 
           # The newsfile lint may be skipped on non PR builds
-          skippable:
-            lint-newsfile
+#          skippable:
+#            lint-newsfile
