[CI] Strip out tests that won't be needed when only using docker images.

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -40,7 +40,7 @@ jobs:
         run: scripts-dev/check_line_terminators.sh
 
   lint-newsfile:
-    if: ${{ github.base_ref == 'develop'  || contains(github.base_ref, 'release-') }}
+    if: ${{ github.base_ref == 'unraid_main'  || contains(github.base_ref, 'release-') }}
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
@@ -67,7 +67,7 @@ jobs:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        python-version: ["3.7", "3.8", "3.9", "3.10"]
+        python-version: ["3.9", "3.10"]
         database: ["sqlite"]
         extras: ["all"]
         include:
@@ -76,7 +76,7 @@ jobs:
             extras: ""
 
           # Oldest Python with PostgreSQL
-          - python-version: "3.7"
+          - python-version: "3.9"
             database: "postgres"
             postgres-version: "10"
             extras: "all"
@@ -124,65 +124,66 @@ jobs:
           -exec echo "::endgroup::" \;
           || true
 
-  trial-olddeps:
-    # Note: sqlite only; no postgres
-    if: ${{ !cancelled() && !failure() }} # Allow previous steps to be skipped, but not fail
-    needs: linting-done
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
-      - name: Test with old deps
-        uses: docker://ubuntu:focal # For old python and sqlite
-        # Note: focal seems to be using 3.8, but the oldest is 3.7?
-        # See https://github.com/matrix-org/synapse/issues/12343
-        with:
-          workdir: /github/workspace
-          entrypoint: .ci/scripts/test_old_deps.sh
-      - name: Dump logs
-        # Logs are most useful when the command fails, always include them.
-        if: ${{ always() }}
-        # Note: Dumps to workflow logs instead of using actions/upload-artifact
-        #       This keeps logs colocated with failing jobs
-        #       It also ignores find's exit code; this is a best effort affair
-        run: >-
-          find _trial_temp -name '*.log'
-          -exec echo "::group::{}" \;
-          -exec cat {} \;
-          -exec echo "::endgroup::" \;
-          || true
-
-  trial-pypy:
-    # Very slow; only run if the branch name includes 'pypy'
-    # Note: sqlite only; no postgres. Completely untested since poetry move.
-    if: ${{ contains(github.ref, 'pypy') && !failure() && !cancelled() }}
-    needs: linting-done
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        python-version: ["pypy-3.7"]
-        extras: ["all"]
-
-    steps:
-      - uses: actions/checkout@v2
-      # Install libs necessary for PyPy to build binary wheels for dependencies
-      - run: sudo apt-get -qq install xmlsec1 libxml2-dev libxslt-dev
-      - uses: matrix-org/setup-python-poetry@v1
-        with:
-          python-version: ${{ matrix.python-version }}
-          extras: ${{ matrix.extras }}
-      - run: poetry run trial --jobs=2 tests
-      - name: Dump logs
-        # Logs are most useful when the command fails, always include them.
-        if: ${{ always() }}
-        # Note: Dumps to workflow logs instead of using actions/upload-artifact
-        #       This keeps logs colocated with failing jobs
-        #       It also ignores find's exit code; this is a best effort affair
-        run: >-
-          find _trial_temp -name '*.log'
-          -exec echo "::group::{}" \;
-          -exec cat {} \;
-          -exec echo "::endgroup::" \;
-          || true
+# This is exclusively a docker image moving forward, so don't run this.
+#  trial-olddeps:
+#    # Note: sqlite only; no postgres
+#    if: ${{ !cancelled() && !failure() }} # Allow previous steps to be skipped, but not fail
+#    needs: linting-done
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v2
+#      - name: Test with old deps
+#        uses: docker://ubuntu:focal # For old python and sqlite
+#        # Note: focal seems to be using 3.8, but the oldest is 3.7?
+#        # See https://github.com/matrix-org/synapse/issues/12343
+#        with:
+#          workdir: /github/workspace
+#          entrypoint: .ci/scripts/test_old_deps.sh
+#      - name: Dump logs
+#        # Logs are most useful when the command fails, always include them.
+#        if: ${{ always() }}
+#        # Note: Dumps to workflow logs instead of using actions/upload-artifact
+#        #       This keeps logs colocated with failing jobs
+#        #       It also ignores find's exit code; this is a best effort affair
+#        run: >-
+#          find _trial_temp -name '*.log'
+#          -exec echo "::group::{}" \;
+#          -exec cat {} \;
+#          -exec echo "::endgroup::" \;
+#          || true
+#
+#  trial-pypy:
+#    # Very slow; only run if the branch name includes 'pypy'
+#    # Note: sqlite only; no postgres. Completely untested since poetry move.
+#    if: ${{ contains(github.ref, 'pypy') && !failure() && !cancelled() }}
+#    needs: linting-done
+#    runs-on: ubuntu-latest
+#    strategy:
+#      matrix:
+#        python-version: ["pypy-3.7"]
+#        extras: ["all"]
+#
+#    steps:
+#      - uses: actions/checkout@v2
+#      # Install libs necessary for PyPy to build binary wheels for dependencies
+#      - run: sudo apt-get -qq install xmlsec1 libxml2-dev libxslt-dev
+#      - uses: matrix-org/setup-python-poetry@v1
+#        with:
+#          python-version: ${{ matrix.python-version }}
+#          extras: ${{ matrix.extras }}
+#      - run: poetry run trial --jobs=2 tests
+#      - name: Dump logs
+#        # Logs are most useful when the command fails, always include them.
+#        if: ${{ always() }}
+#        # Note: Dumps to workflow logs instead of using actions/upload-artifact
+#        #       This keeps logs colocated with failing jobs
+#        #       It also ignores find's exit code; this is a best effort affair
+#        run: >-
+#          find _trial_temp -name '*.log'
+#          -exec echo "::group::{}" \;
+#          -exec cat {} \;
+#          -exec echo "::endgroup::" \;
+#          || true
 
   sytest:
     if: ${{ !failure() && !cancelled() }}
@@ -205,26 +206,40 @@ jobs:
       fail-fast: false
       matrix:
         include:
-          - sytest-tag: focal
+#          - sytest-tag: focal
 
-          - sytest-tag: focal
+#          - sytest-tag: focal
+#            postgres: postgres
+
+#          - sytest-tag: testing
+#            postgres: postgres
+
+          - sytest-tag: buster
             postgres: postgres
+            workers: monolith
 
-          - sytest-tag: testing
+#          - sytest-tag: buster
+#            postgres: postgres
+#            workers: monolith
+#            redis: redis
+
+          - sytest-tag: buster
             postgres: postgres
-
-          - sytest-tag: focal
-            postgres: multi-postgres
             workers: workers
+
+#          - sytest-tag: buster
+#            postgres: postgres
+#            workers: workers
+#            redis: redis
 
           - sytest-tag: buster
             postgres: multi-postgres
             workers: workers
 
-          - sytest-tag: buster
-            postgres: postgres
-            workers: workers
-            redis: redis
+#          - sytest-tag: buster
+#            postgres: multi-postgres
+#            workers: workers
+#            redis: redis
 
     steps:
       - uses: actions/checkout@v2
@@ -355,7 +370,6 @@ jobs:
       - lint-crlf
       - lint-newsfile
       - trial
-      - trial-olddeps
       - sytest
       - export-data
       - portdb
